// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvOJc2td1aYeJQypkCejpEAsaEM00OS0c',
    appId: '1:464313419899:web:e9a69bdfa87fca4741fade',
    messagingSenderId: '464313419899',
    projectId: 'relay-c4990',
    authDomain: 'relay-c4990.firebaseapp.com',
    databaseURL: 'https://relay-c4990-default-rtdb.firebaseio.com',
    storageBucket: 'relay-c4990.appspot.com',
    measurementId: 'G-J0T3R8HDQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHWIOLEo27cO387xTLDKMAWmxu1PuU1xE',
    appId: '1:464313419899:android:d30c40e812371ec641fade',
    messagingSenderId: '464313419899',
    projectId: 'relay-c4990',
    databaseURL: 'https://relay-c4990-default-rtdb.firebaseio.com',
    storageBucket: 'relay-c4990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbFtRY90rgj_4no7ufqv6rQd943d95T9U',
    appId: '1:464313419899:ios:61241597a6d5d9c041fade',
    messagingSenderId: '464313419899',
    projectId: 'relay-c4990',
    databaseURL: 'https://relay-c4990-default-rtdb.firebaseio.com',
    storageBucket: 'relay-c4990.appspot.com',
    iosClientId: '464313419899-caf7fpkkobbhpf4kl942b4rb0cl5vq0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbFtRY90rgj_4no7ufqv6rQd943d95T9U',
    appId: '1:464313419899:ios:61241597a6d5d9c041fade',
    messagingSenderId: '464313419899',
    projectId: 'relay-c4990',
    databaseURL: 'https://relay-c4990-default-rtdb.firebaseio.com',
    storageBucket: 'relay-c4990.appspot.com',
    iosClientId: '464313419899-caf7fpkkobbhpf4kl942b4rb0cl5vq0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvOJc2td1aYeJQypkCejpEAsaEM00OS0c',
    appId: '1:464313419899:web:850d4355936f7ee441fade',
    messagingSenderId: '464313419899',
    projectId: 'relay-c4990',
    authDomain: 'relay-c4990.firebaseapp.com',
    databaseURL: 'https://relay-c4990-default-rtdb.firebaseio.com',
    storageBucket: 'relay-c4990.appspot.com',
    measurementId: 'G-QLJM3VFXQV',
  );

}